---
- hosts: cluster
  become: yes
  gather_facts: true
  
  tasks:

    - name: download_config of microk8s
      import_role:
        name: install_microk8s
        tasks_from: download_config.yml

