all:
  vars:
    ansible_user: root
    ansible_connection: ssh
    ansible_ssh_extra_args: "-o ForwardAgent=yes"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.darklab

  children:
    cluster:
      hosts: 5.161.43.86
      vars:
        varenv: staging
        app: darklab
